# Generated by Django 4.1.3 on 2022-11-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("economy", models.TextField(max_length=500)),
                ("weather", models.TextField(max_length=500)),
                ("politics", models.TextField(max_length=500)),
            ],
        ),
    ]
