# Generated by Django 4.1.3 on 2022-11-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="new",
            name="economy",
        ),
        migrations.RemoveField(
            model_name="new",
            name="politics",
        ),
        migrations.RemoveField(
            model_name="new",
            name="weather",
        ),
        migrations.AddField(
            model_name="new",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="new",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="new",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
