# Generated by Django 4.1.3 on 2022-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_new_economy_remove_new_politics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
        migrations.AddField(
            model_name="student",
            name="language",
            field=models.CharField(
                choices=[
                    ("nepali", "Nepali"),
                    ("english", "English"),
                    ("chinese", "Chinese"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="new",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
